name: lifetime_faq_ci_dev_pipeline

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      flow_type:
        type: string
        description: "The flow usecase to execute"
        required: true
        default: "lifetime_faq"
      deployment_type:
        type: string
        description: "Determine type of deployment - aml, aks, docker, webapp"
        required: true
        default: "aml"
  push:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'lifetime_faq/**'

#=====================================
# Execute platform_ci_dev_workflow workflow for experiment, evaluation and deployment of flows
#=====================================
jobs:
  execute-platform-flow-ci:
    uses: ./.github/workflows/platform_ci_dev_workflow.yml
    with:
      env_name: ${{ inputs.env_name || 'dev'}}
      flow_type: ${{ inputs.flow_type || 'lifetime_faq' }}
      deployment_type: ${{ inputs.deployment_type|| 'aml' }}
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      connection_details: ${{ secrets.COMMON_DEV_CONNECTIONS }}
      registry_details: ${{ secrets.DOCKER_IMAGE_REGISTRY }}
